[package]
name = "enum_primitive_derive"
version = "0.1.0"
authors = ["Christopher Breeden <github@u.breeden.cc>"]

[lib]
proc-macro = true

[dependencies]
syn = "0.10"
quote = "0.3"

[dev-dependencies]
enum_primitive = "0.1.1"